GET http://localhost:3000/api/hello
Accept: application/json

###

POST http://localhost:3000/api/hello
Host: foo.example
Content-Type: application/json

{
  "name": "charlie",
  "password": "woof"
}

###

POST http://192.168.178.28:3000/api/login
Host: foo.example
Content-Type: application/json

{
  "name": "pascal",
  "password": "12"
}
